### ISSUE TITLE
evaluate validations and add required

### ISSUE THREAD

**Issue by jurrack** [bootstrap-ruby/rails-bootstrap-forms#143]
wouldn't it be great if this gem would add input required attribute and label asterisk for fields with validation?

**Comment by Shoroh** [comment]
If I have condition like this:
```ruby
validates :value, presence: true, if: Proc.new { |ad_property| ad_property.ad_field.required? }
```
:value is always required.

**Comment by mattbrictson** [comment]
Cleaning up old unanswered issues. If this question is still relevant, please reopen.
