### ISSUE TITLE
hide_label: :true doesn't work for checkboxes?

### ISSUE THREAD

**Issue by Qbd** [bootstrap-ruby/rails-bootstrap-forms#149]
<%= f.check_box :attribute, hide_label: :true %> doesn't seem to work. Is there something I'm missing?

**Comment by onebree** [comment]
@Qbd I am not sure if the gem has updated since your post, but try: `hide_label: true` instead. True can be typed as a boolean, not just a symbol.

**Comment by Qbd** [comment]
Thanks for the help guys, I'm pretty sure I found a workaround but should I ever come across the problem again, I'll give more details.

Sorry, still kind of new at this whole open source thing

**Comment by onebree** [comment]
@Qbd, please post your workaround, in case others have a similar issue. Alongside your current version of the gem :-)

**Comment by Qbd** [comment]
I believe my workaround was to not use bootstrap forms..

I have a situation where a user can view tabular data and change certain boolean properties via AJAX submissions.

I just used the default form builder and declared f.checkbox.

At least looking back at my commits at that point in time, that seems to be the only major work I was doing with checkboxes.

**Comment by abrambailey** [comment]
:(

**Comment by CreativelyCloudy** [comment]
Hi all,

Had the same problem...found setting label: '' (empty quotes) did the trick.

**Comment by chao-mu** [comment]
The above work arounds (specifying an empty label) do not work for me because they still render the label tag, throwing off my alignment. My work around was to just render a raw html checkbox and hope naming doesn't change. :-(.

My use case was checkboxes in a table.

**Comment by chao-mu** [comment]
Another workaround could have been to "display: none" on the label with css.
