### ISSUE TITLE
Check boxes not checked on edit with collection_check_boxes

### ISSUE THREAD

**Issue by krsyoung** [bootstrap-ruby/rails-bootstrap-forms#151]
I have an association using collection_check_boxes based on a model that is using a non-standard id function (:to_params).  I was having a problem where the values that had been previously selected were not showing as selected when editing the form.

After digging through the code I found that I can make it work with the following:

```
<%= f.collection_check_boxes :people, People.all, :to_param, :full_name, { checked: @event.people.map(&:to_param) } %>
```

Basically adding the "checked" parameter to the options did the trick.  That allowed the `inputs_collection` method in `form_builder.rb` to do its thing.

I haven't found this described in the broader rails documentation -- wondering two things:
1. Did i just do something wrong in the first place?
2. Worth submitting a pull request to have the documentation updated to reflect the "checked" option?

Thanks!
-Chris

**Comment by njt1982** [comment]
Is this really how we're meant to do this?

**Comment by mattbrictson** [comment]
The Bootstrap form helpers should follow the same behavior as the original Rails form helpers whenever possible. If this is not the case here, then I would consider it a bug.

Let me know if you have an idea of how to fix this, or even better, please open a PR for us to review.

**Comment by pachonk** [comment]
FWIW, you can just do `checked: value` in current ruby I believe.

**Comment by mattbrictson** [comment]
Cleaning up old unanswered issues. If this question is still relevant, please reopen.
