### ISSUE TITLE
Label column class option in form builder is not respected in form_group offset

### ISSUE THREAD

**Issue by ljachymczyk** [bootstrap-ruby/rails-bootstrap-forms#152]
Hi, 

Seems that following code is not working as expected:

``` ruby
= bootstrap_form_for @user, :layout => :horizontal, :label_col => "col-sm-4", :control_col => "col-sm-8" do |f|
  = f.form_group do
    = f.check_box :active
```

This outputs the code where checkbox is offsetted using 'col-sm-offset-2' (default) instead 'col-sm-offset-4' (based on label_col option in form builder).

The workaround is to explicitely set label_col again in `form_group`. 

I guess this can be fixed by following change in `form_group` method. Line

``` ruby
control_offset = offset_col(/([0-9]+)$/.match(options[:label_col] || default_label_col))
```

can be changed to 

``` ruby
control_offset = offset_col(/([0-9]+)$/.match(options[:label_col] || label_col || default_label_col))
```

**Comment by ezuhaib** [comment]
The issue still persists...

**Comment by potenza** [comment]
Sorry, I've been swamped and haven't had much time to work on this. I'll gladly accept a PR with some  tests for this change if one of you has the time? Thanks.

**Comment by mattbrictson** [comment]
Cleaning up old unanswered issues. If this question is still relevant for Bootstrap v4, please reopen.
