### ISSUE TITLE
Is it possible to set the height size for select, input, etc ?

### ISSUE THREAD

**Issue by mgtf** [bootstrap-ruby/rails-bootstrap-forms#167]
Using : http://getbootstrap.com/css/#forms-control-sizes

Thanks a lot

**Comment by GBH** [comment]
Interested in this as well. It needs to be applied on `.form-group` container though, not on the input element directly. I feel there should be an option for this.

**Comment by kylefox** [comment]
I was able to change the form control size by passing the `control_class` param:

```erb
<%= f.text_field :name, control_class: "form-control input-lg" %>
```

Figured I'd add it here in case anyone else came across this issue looking for a solution!

**Comment by mattbrictson** [comment]
Cleaning up old unanswered issues. If this question is still relevant for Bootstrap v4, please reopen.
