### ISSUE TITLE
Optimize for checkbox's i18n

### ISSUE THREAD

**Issue by chouandy** [bootstrap-ruby/rails-bootstrap-forms#177]
I have a problem for checkbox's i18n.
If my code like below, checkbox's label is not useful

```
# view haml file, model is User
= f.check_box :remember_me
# locales file
zh-TW:
  helpers:
    label:
      user:
        ...
        remember_me: '保持登入狀態'
```

but it is useful by below i18n.

```
  ...
  activerecord:
      attributes:
        user:
          remember_me: '保持登入狀態'
  ...
```

Finially, I found that `rails-bootstrap-forms` checkbox's label source codes is only use `human_attribute_name` method. 
source code <a href="https://github.com/bootstrap-ruby/rails-bootstrap-forms/blob/master/lib/bootstrap_form/form_builder.rb#L107" target="_blank">here</a>

The official `label` source code : <a href="https://github.com/rails/rails/blob/7a085dac2a2820856cbe6c2ca8c69779ac766a97/actionview/lib/action_view/helpers/tags/label.rb#L38" target="_blank">here source code</a>

It is also checking locale code `helpers.label.object_name.name`

So, I had cloned rails-bootstrap-forms source codes to try, finially, the below codes is good work for me.
Just to provide rails-bootstrap-forms teams for reference.

old codes

```
      ...
      label_content = block_given? ? capture(&block) : options[:label]
      html.concat(" ").concat(label_content || (object && object.class.human_attribute_name(name)) || name.to_s.humanize)
      ...
```

new codes

```
      ...
      if block_given?
        label_content = capture(&block)
      else
        label_content = if options[:label].blank?
                          I18n.t("#{object_name}.#{name}", :scope => "helpers.label").presence
                        else
                          @content.to_s
                        end
        label_content ||= if object && object.class.respond_to?(:human_attribute_name)
                            object.class.human_attribute_name(name)
                          end
        label_content ||= name.to_s.humanize
      end
      html.concat(" ").concat(label_content)
      ...
```

**Comment by mattbrictson** [comment]
Cleaning up old unanswered issues. If this question is still relevant, please reopen.
