### ISSUE TITLE
ruby code in Help Text

### ISSUE THREAD

**Issue by aditya01933** [bootstrap-ruby/rails-bootstrap-forms#179]
How can i include the following ruby code in Help text:-

```
       <% if @validatable %>
        <em>(<%= @minimum_password_length %> characters minimum)</em>
        <% end %>
```

I want HTML output as

Password (8 characters minimum)

But its showing

 Password
 (8 characters minimum)
 Any help ??

**Comment by mattbrictson** [comment]
Cleaning up old unanswered issues. If this question is still relevant, please reopen.
