### ISSUE TITLE
appending an input with a .input-lg and .btn-lg should add .input-group-lg

### ISSUE THREAD

**Issue by troytc** [bootstrap-ruby/rails-bootstrap-forms#181]
Without this class, the problem in [this issue](https://github.com/twbs/bootstrap/issues/13680) occurs.

![Example](https://cloud.githubusercontent.com/assets/2413031/3079428/ecad4d78-e499-11e3-86d9-944b760b638c.png)

The class for the input group needs to be `.input-group .input-group-lg`.

**Comment by mattbrictson** [comment]
Cleaning up old unanswered issues. If this question is still relevant for Bootstrap v4, please reopen.
