### ISSUE TITLE
Glyphicon icon doesn't works with the submit

### ISSUE THREAD

**Issue by piotrgorecki** [bootstrap-ruby/rails-bootstrap-forms#187]
Hello
I try to add a glyphicon icon to the submit button in this way:
`f.submit :search, icon: "search"`
But I just get button without any icon, like this:
`<input class="btn btn-default" icon="search" name="commit" type="submit" value="search" />`

I'm not sure that adding an icon to the submit is either a good or a legal operation.

**Comment by sureseam** [comment]
Glyphicons are a Bootstrap feature so you need to consult the getbootstrap website.
The HTML you need to generate is more like this:
        <button type="submit" class="btn btn-default btn-sm">
          <span class="glyphicon glyphicon-search" aria-hidden="true"> </span>
        </button>

With the bootstrap_form notation it may look more like the following: 
<%= f.submit raw('<span class="glyphicon glyphicon-search" aria-hidden="true"> </span>'), 
     class: "btn btn-default btn-sm" %>

Hope that helps!

**Comment by sureseam** [comment]
On reflection this issue could now probably be closed.

**Comment by onebree** [comment]
@piotrgorecki Using HAML, here is how I was able to create the following:
![screenshot from 2015-02-03 09 19 16](https://cloud.githubusercontent.com/assets/9038433/6021712/c2d68128-ab85-11e4-891d-5bffaa80981c.png)
```haml
// bootstrap_form_for/tag argument
  %a{class: "btn btn-danger", type: "submit", name: "commit"}
    %span.glyphicon.glyphicon-record
    Record
```

For your specific code block, this is what I would suggest:
```haml
  %a{class: "btn btn-default", type: "submit", name: "commit", value: "search"}
    %span.glyphicon.glyphicon-search
    Search
```

**Comment by victorhazbun87** [comment]
he is asking for a submit not a link @onebree ....

**Comment by onebree** [comment]
Sorry. I must have confused it with the `type` attribute that my button has.

**Comment by reubenbrown** [comment]
@piotrgorecki You could also do 
````
= button_tag(class: 'btn btn-default')
    %span.glyphicon.glyphicon-search
    Some text for your button
````
