### ISSUE TITLE
.required class not appearing when the field is required

### ISSUE THREAD

**Issue by duncannz** [bootstrap-ruby/rails-bootstrap-forms#188]
The README says:

>A label that is associated with a required field is automatically annotated with a required CSS class. You are free to add any appropriate CSS to style required fields as desired.
> [...]
> The label required class is determined based on the definition of a presence validator with the associated model attribute. Presently this is one of: ActiveRecord::Validations::PresenceValidator or ActiveModel::Validations::PresenceValidator.

This behaviour does not occur for me. My version of bootstrap_forms is up to date (2.2.0). In this example I have a model called `questions` with just one field called `title`.

### Relevant files

app/models/question.rb

```ruby
class Question < ActiveRecord::Base
  validates :title, presence: true       # I also tried using `validates_presence_of :title`
end
```

app/views/questions/_form.html.erb

```erb
<%= bootstrap_form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.text_field :title %>
  <%= f.submit %>
<% end %>
```

Output

```html
<div class="form-group"><label class="control-label" for="question_title">Title</label><input class="form-control" type="text" name="question[title]" id="question_title" /></div>
```

Notice that the class `required` is missing from the `<label>`. However Rails does definitely recognise that the field is required because when I submit the form empty I do get the "field can't be blank" error.

Citing #170, #176.

**Comment by rikkipitt** [comment]
I seem to be having this issue too... have you found why this might be the case yet, @duncannz ?

**Comment by duncannz** [comment]
No I haven't got a solution @rikkipitt - awaiting dev comment.

**Comment by rikkipitt** [comment]
Thanks for the quick reply. Hopefully between you, myself and the repo owner, we'll sort it out!

**Comment by krsyoung** [comment]
Hey folks, did you try to pull from master vs rubygems?  Not that is solves the problem but at least will confirm that it is just a matter of getting ruby gems caught up.

**Comment by duncannz** [comment]
@krsyoung I did pull from rubygems, and just did a quick test app that pulled from git, and can verify the issue is indeed fixed in the git version. So it's just a matter of getting rubygems caught up.

thanks :)

**Comment by krsyoung** [comment]
Thanks for confirming @duncannz!  I'm sure @potenza will post an updated version of the gem to rubygems when time permits (there have been a number of people getting caught up with the README not in sync with the 2.2.0 gem).

For the time being, I have a couple of applications pulling directly from master to avoid the lag (so far so good).

**Comment by fabn** [comment]
+1

**Comment by Stajor** [comment]
+1

**Comment by potenza** [comment]
Hey all, sorry for the delay. I just pushed 2.3.0 to rubygems. Hope that helps!

**Comment by databurj** [comment]
validates :title, presence: true should be validates :title, :presence => true
hope so this will work
