### ISSUE TITLE
ActiveRecord does not need to be defined

### ISSUE THREAD

**Issue by trunda** [bootstrap-ruby/rails-bootstrap-forms#189]
If someone is using Rails without ActiveRecord (with Sequel for example), [this line](https://github.com/bootstrap-ruby/rails-bootstrap-forms/blob/master/lib/bootstrap_form/form_builder.rb#L268) will fail.

```
uninitialized constant BootstrapForm::FormBuilder::ActiveRecord

/Users/trunda/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/rails-bootstrap-forms-5e498df2a3e0/lib/bootstrap_form/form_builder.rb:268:in `required_attribute?'
/Users/trunda/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/rails-bootstrap-forms-5e498df2a3e0/lib/bootstrap_form/form_builder.rb:330:in `generate_label'
/Users/trunda/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/rails-bootstrap-forms-5e498df2a3e0/lib/bootstrap_form/form_builder.rb:181:in `block in form_group'
```

**Comment by krsyoung** [comment]
Thanks for sharing @trunda.  I'm not familiar with using Sequel.  Could you post the relevant changes in your Gemfile (assuming it is easy to set-up / reproduce)?

Also, it looks like Sequel is much more user defined in the model validation handling  .. if you are familiar with it, would you say the best approach is to not automatically handle defining required fields if the app is using Sequel?  

Or maybe you have an idea how we could inject the ```required``` css class using a Sequel friendly way?

**Comment by sgnn7** [comment]
@krsyoung I'm having the same error/problem using MongoMapper

**Comment by sgnn7** [comment]
@krsyoung CR ready:
- https://github.com/bootstrap-ruby/rails-bootstrap-forms/issues/200

**Comment by sgnn7** [comment]
@trunda The patch for this has been merged. Can you try it out with code from master?

**Comment by trunda** [comment]
@sgnn7 I am no longer using this gem, anyway your fix will definitely work :+1: . Thank you.
