### ISSUE TITLE
bootstrap_form_tag and collection_select giving bad name

### ISSUE THREAD

**Issue by burnt43** [bootstrap-ruby/rails-bootstrap-forms#193]
Hello, I have a form that isn't associated with an object and therefore I am using bootstrap_form_tag. On this form I have a button where I can add different search filters which will add an an additional dropdown box when clicked. This means I can have an indefinite amount of dropdowns. My code abbreviated looks like the following:

<pre>
= bootstrap_form_tag(bsf_opts(url: "/recorded_calls", method: :post)) do |f|
...
  %td= f.collection_select "durations_greater_less[]", @duration_options, :last, :first, hide_label: true
</pre>

The html that the f.collection_select generates is found and cloned and added to the page with jQuery when the user clicks a button to add a new filter. The problem is the html that is generated has what I think is an incorrect name. Below is the html that comes out. the name is "[durations_greater_less[]]". This is a problem because lets says a user makes 5 of these dropdowns, I expect to receive as params an array for durations_greater_less, but since the name is enclosed with "[]" the params is not an array, it is a single value. I expect the name to be just durations_greater_less[].

``` html
<select class=form-control name=[durations_greater_less[]] id=_durations_greater_less[]>
  <option value=gt>Greater Than</option>
  <option value=lt>Less Than</option>
</select>
```

I tried to trace this out in the code, but I got stuck in the form_group method on form_builder.rb on the line 

<pre>
control = capture(&block).to_s
</pre>

I see that capture is delegated to @template, but I do not know where @template comes from. Before  the aforementioned line I did capture(1,2) just so it would raise an exception that I had the wrong number of args. In the backtrace I saw capture was going to code in another gem, so I'm not sure if it is the other gem where the issue lies or maybe there is just some data in bootstrap-forms I need to change to get this working.

In the meantime I can hack a solution with using rails select_tag and I'll set the classes manually to have it bootstrap styled.

**Comment by burnt43** [comment]
If this was too complicated, allow me to clarify with a easier to understand example. Imagine I have a form where there is a button that says "Add Fruit". When clicked it will inset a text_field named amounts[] and a dropdown a fuits named fruits[]. So you can do something like

1. Hit "Add Fruit"
2. Enter "5" in the text field
3. Select "Banana "from the drop down
4. Hit "Add Fruit"
5. Enter "2" in the text field
6. Enter "Pineapple" from the drop down
7. Hit Submit

The params will be {amounts => ["5","2"], fruits => nil}

**Comment by parhs** [comment]
this might be coming from rails framework...

**Comment by mattbrictson** [comment]
Cleaning up old unanswered issues. If this question is still relevant, please reopen.
