### ISSUE TITLE
rails-bootstrap-forms vs simple_form?

### ISSUE THREAD

**Issue by sameerkhanna** [bootstrap-ruby/rails-bootstrap-forms#195]
I've been experimenting with rails-bootstrap-forms for a few days and it's been very easy to use. I'm just curious if the author could detail the major differences between this and using simple_form with bootstrap? Are there any limitations I should be aware of? Thanks.

**Comment by potenza** [comment]
hi @sameerkhanna, I don't think I'd be able to describe the major differences as I've never used simple_form before. This project grew out of a simple form builder I had created years ago to help with bootstrap markup.
