### ISSUE TITLE
Add glyphicon inside label for checkbox

### ISSUE THREAD

**Issue by onebree** [bootstrap-ruby/rails-bootstrap-forms#196]
Here is my original code, which produces: 
![screenshot from 2015-02-03 09 33 48](https://cloud.githubusercontent.com/assets/9038433/6022000/cb09b534-ab87-11e4-9549-9f3d7dea5c0b.png)

``` haml
  = f.form_group do
    = f.check_box :present_menu
```

However, I want the label to include `glyphicon-asterisk`, instead of `(*)` (for readability). The friendly-label is for `:present_menu` is generated in our locales file. Because the locales file is in YML, I know that I cannot insert the glyphicon there. (And it would affect further presence of that label in the app.)

**Comment by mattbrictson** [comment]
Cleaning up old unanswered issues. If this question is still relevant, please reopen.
