### ISSUE TITLE
'collection_check_boxes' adds a hidden element to the form in the latest revision

### ISSUE THREAD

**Issue by arpitadhundia** [bootstrap-ruby/rails-bootstrap-forms#197]
The following piece of code worked perfectly with Ruby 2.1.2, Rails 4.2 and bootstrap_form revision 44f36a224d6a2d63718c017426c40c50a6b1eb04:-

```
<%= f.collection_check_boxes :steps, Event::steps, :name, :display, :label => 'Steps' %>
```

But after upgrading to the latest revision of bootstrap_form, I see that the 'collection_check_boxes' adds a hidden element to my form. Here is the additional html I see:-

```
<input value="" multiple="multiple" type="hidden" name="wizard_create_event_base_order_settings_form[steps][]" id="wizard_create_event_base_order_settings_form_steps">
```

So on form submission, there is an extra element in the array that represents this collection. Basically even though I have 6 checkboxes checked, on form submission my array has 7 elements with the first element being an empty value(from the hidden field).

Out of curiosity I looked at the implementation for 'collection_check_boxes' in the latest version and I see it has been changed to add a 'hidden_field' call. Here is the code:-

```
def collection_check_boxes(*args)
      html = inputs_collection(*args) do |name, value, options|
        options[:multiple] = true
        check_box(name, options, value, nil)
      end
      hidden_field(args.first,{value: "", multiple: true}).concat(html)
 end
```

This change breaks my code as I don't expect an additional empty element in the array. I was wondering if this behavior is intentional or a defect? Could someone elaborate on it?

Thanks!

**Comment by onebree** [comment]
To make this more readable, please use markdown for your code blocks, and specify the language for each block.

**Comment by arpitadhundia** [comment]
@onebree - is this better?

**Comment by onebree** [comment]
Yes

**Comment by mattbrictson** [comment]
Cleaning up old unanswered issues. If this question is still relevant, please reopen.
