### ISSUE TITLE
How to show to text fields with labels in same row..

### ISSUE THREAD

**Issue by daBayrus** [bootstrap-ruby/rails-bootstrap-forms#198]
hi, great gem.. i'm able to output the desired form as shown in the image, except for the ones with two text fields in same row/line (Provider ID and Group ID, and State and Zip).. the form is form-horizontal and I tried layout: :inline for the said fields but did not work..

![image](https://cloud.githubusercontent.com/assets/751749/6056707/ba9cb682-ad4f-11e4-964e-f80e6a9d99f4.png)

**Comment by datWav** [comment]
You can do something like:
```erb
.row
  .col-md-6
    = f.text_field :provider_site_id
  .col-md-6
    = f.text_field :group_id
```

**Comment by mattbrictson** [comment]
Cleaning up old unanswered issues. If this question is still relevant, please reopen.
