### ISSUE TITLE
label_class:  adds class to the wrong element in the form group.

### ISSUE THREAD

**Issue by rhnorment** [bootstrap-ruby/rails-bootstrap-forms#201]
```
<%= f.email_field :email, label_class:'text-warning' %>
```

The label_class function is adding "label_class=" to the email input element and not the label.  

Any suggestions?

**Comment by danarrington** [comment]
Hi @rhnorment, I had the same problem, and it looks like it's been addressed in 2.3.

**Comment by mattbrictson** [comment]
Cleaning up old unanswered issues. If this question is still relevant, please reopen.
