### ISSUE TITLE
required_attribute doesn't play well with Ransack search object

### ISSUE THREAD

**Issue by bborn** [bootstrap-ruby/rails-bootstrap-forms#203]
When using a bootrap_form_for on a Ransack search object, the required_attribute method fails (because Ransack::Search doesn't have a `validators_on` method). Can `required_attribute?` check to see if the object support the validators method before proceeding? Something like:

```
def required_attribute?(obj, attribute)
    return false unless obj.respond_to?(:validators_on)
```

**Comment by stevenou** [comment]
+1. Same issue when applying to UserSession model from AuthLogic.

**Comment by apm31** [comment]
For the issue with UserSession and Authlogic, adding 

    include ActiveModel::Validations

appears to have solved the problem.

**Comment by opensourceame** [comment]
This is also a problem using bootstrap_form 2.3.0 if you're using an alternative ORM like Sequel. It was fine in 2.2.0.

**Comment by mattbrictson** [comment]
Cleaning up old unanswered issues. If this question is still relevant, please reopen.
