### ISSUE TITLE
Remove .required class from label?

### ISSUE THREAD

**Issue by Stajor** [bootstrap-ruby/rails-bootstrap-forms#205]
How can I remove .required class from label?
I want the presence validation in my main form, but i need to remove .required from search form

```
<%= f.select :status, Campaign.statuses.collect{|status, i| [t(status), i] }, {include_blank: 'All', label_class: 'control-label'}, {name: :status, wrapper_class: 'col-md-6'} %>
```

Still render with . required
```
<label class="control-label control-label required" for="campaign_status">Status</label>
```

**Comment by krsyoung** [comment]
Hi @Stajor, right now it is determined solely on the field having a presence validator -- there is no way to exclude it.

A couple of thoughts:
1. we figure out how to exclude it :-)
2. you try a different version of CSS that doesn't select the Status label when in a Search form
3. avoid using the presence validator on the Status field if in Search mode

Just curious.  The Status field is required but the class is causing you grief or you don't want to show an '*'?  Do you have different logic making the Status field optional when in the Search context?

**Comment by Stajor** [comment]
Yes the field is optional only in search context.
For now I can fix it with css.
I'm waiting for next update :)
Thank you for great and useful gem
