### ISSUE TITLE
wrapper_class not working for select's

### ISSUE THREAD

**Issue by reneweteling** [bootstrap-ruby/rails-bootstrap-forms#208]
hey there,

````
  = f.date_select :start_time, wrapper: { class: 'has-warning', data: { foo: 'bar' } }  <-- not working
  = f.text_field :description, wrapper: { class: 'has-warning', data: { foo: 'bar' } }  <-- works
````
Thanks!

**Comment by datWav** [comment]
There is something diffrent for the two calls. For the FIELD_HELPERS (text_field) `form_group_builder(name, options) do` and DATE_SELECT_HELPERS (date_select) `form_group_builder(name, options, html_options) do`.
The correct call for you should be `= f.date_select :start_time,{}, wrapper: { class: 'has-warning', data: { foo: 'bar' } }`

**Comment by reneweteling** [comment]
Aii.... so it was probably a RTFM on my part. Mea culpa! Thanks for the solution!
