### ISSUE TITLE
HTML code on help section

### ISSUE THREAD

**Issue by Soullivaneuh** [bootstrap-ruby/rails-bootstrap-forms#211]
Hi.

I have the following form code:

``` haml
  = f.text_area :redirect_uri, help: 'Use one line per URI'
```

I have some extra conditional help to add, based on this old code:

``` haml
  - if Doorkeeper.configuration.native_redirect_uri
  %span.help-block
    Use
    %code= Doorkeeper.configuration.native_redirect_uri
    for local tests
```

How can I override the help block to do some logic inside? Is that possible with this library?

Thanks.

**Comment by datWav** [comment]
At this point this is not possible. Maybe you should call a helper method for this logic.

**Comment by Soullivaneuh** [comment]
> Maybe you should call a helper method for this logic.

Do you have some recommendations of how this helper should be? Thanks.

**Comment by datWav** [comment]
Idk...Maybe something like this one (not tested):
```ruby
def method_name help_text, condition, condition_help_text
  if condition
    help_text.concat(condition_help_text)
  end
  help_text 
end
```

**Comment by Soullivaneuh** [comment]
@datWav So something separated from the form? Not the must isn't it?

Do you think html help block could be easily implemented on this library?

Regards

**Comment by datWav** [comment]
At the moment it is only possible with a separated form. 
How should the method call be?

**Comment by mattbrictson** [comment]
Cleaning up old unanswered issues. If this question is still relevant, please reopen.
