### ISSUE TITLE
Static control without label

### ISSUE THREAD

**Issue by Soullivaneuh** [bootstrap-ruby/rails-bootstrap-forms#212]
With the following code:

``` haml
  = f.static_control do
    = link_to '#', class: 'js-toggle-colors-link' do
      Customize colors
```

We got this error:

```
undefined method `humanize' for nil:NilClass
```

A label option must be set to get it work.

Could be nice to have static control without label, isn't it?

Thanks.

**Comment by datWav** [comment]
You need to pass a symbol to the method. `= f.static_control :colors do`

**Comment by mattbrictson** [comment]
Cleaning up old unanswered issues. If this question is still relevant, please reopen.
