### ISSUE TITLE
Unwanted space with hide_label option on inline form

### ISSUE THREAD

**Issue by Soullivaneuh** [bootstrap-ruby/rails-bootstrap-forms#214]
With the following code:

``` haml
= bootstrap_form_tag url: admin_groups_path, method: :get, layout: :inline do |f|
  = f.hidden_field :sort, value: @sort
  = f.text_field :name, value: params[:name], hide_label: true
  = f.primary 'Search'
```

We get this:

![rails_bootstrap_form_inline_failed](https://cloud.githubusercontent.com/assets/1698357/6917905/506672ce-d7a9-11e4-9470-3568a1bbd9fc.png)

Is that an issue or something I did wrong?

Thanks.

**Comment by randx** [comment]
Looks like an issue. http://getbootstrap.com/css/#forms-inline

**Comment by mattbrictson** [comment]
Cleaning up old unanswered issues. If this question is still relevant, please reopen.
