### ISSUE TITLE
Enable auto label on form_group instead of checkbox_field

### ISSUE THREAD

**Issue by Soullivaneuh** [bootstrap-ruby/rails-bootstrap-forms#216]
On a horizontal form, in order to have a label on the left for checkboxes like the other inputs, we have to do this:

``` haml
= f.form_group :can_create_group, label: { text: 'Can create group' } do
  = f.check_box :can_create_group
```

It's works, but we have to set the label manually, this is not auto generated like check_box does.

Idea: Add an option to set the auto check_box label on the form_group.

Not sure if i'm clear, please tell me if you want more details.

Btw, the actual checkbox_label can't be deleted. Related to #161.

Thanks.

**Comment by mattbrictson** [comment]
Cleaning up old unanswered issues. If this question is still relevant, please reopen.
