### ISSUE TITLE
f.text_area_without_bootstrap not render "error" block

### ISSUE THREAD

**Issue by laerciocrestani** [bootstrap-ruby/rails-bootstrap-forms#218]
Hello!
I use the "_without bootstrap" to render the textarea without the client boostrap form like this in the attached image:
![captura de tela 2015-04-10 as 14 26 07](https://cloud.githubusercontent.com/assets/1430869/7093213/909756ce-df8d-11e4-94ee-da90283ee19b.png)
Unidade, Hardware and software have validations!
When it is not completed and returned with error I can not list the error in text_area, Any help?

**Comment by datWav** [comment]
Correct me if I'm wrong...but if you render the text area without bootstrap the helper methods to view the errors are skipped. You must add the the stuff by yourself.

**Comment by laerciocrestani** [comment]
I did not understand, friend!
is not showing the error message when _without_bootstrap use (: hardware and: software)
Follow my _form.slim
```
= bootstrap_form_for(@obj, layout: :horizontal, label_col: "col-sm-3", control_col: "col-sm-9", html: { id: 'new-edit' }) do |f|
		- if @obj.errors.any?
			.col-lg-6
				.alert.alert-danger.fade.in
					button.close type="button" data-dismiss="alert" aria-hidden="true" 
						| &times;
					h4=t :form_title_error
					p= pluralize(@obj.errors.count, 'erro foi encontrado.', 'erros foram encontrados.')
		.col-lg-6
			= f.form_group :published, label: { text: "Ativo" } do
				.btn-group data-toggle="buttons"
					label.btn.yes-no.btn class=((@obj.ativo? or params[:action] == 'new') ? "btn-success active" : "btn-warning")
						= f.check_box_without_bootstrap :ativo
						= @obj.ativo? ? '<span>Sim</span>'.html_safe : '<span>Não</span>'.html_safe
			=f .collection_select :unidade_id, Unidade.all, :id, :unidade_computador
			= f.text_field :numero, label: "Número"
			= f.text_field :data_aquisicao, label: "Data de Aquisição", class:"data"
		.col-lg-6
			.row
				.col-lg-6
					h2 Hardware
					= f.text_area_without_bootstrap :hardware, class: 'form-control', rows: 5
				.col-lg-6
					h2 Software
					= f.text_area_without_bootstrap :software, class: 'form-control', rows: 5
```

**Comment by mattbrictson** [comment]
`_without_bootstrap` means you get the default Rails form helper behavior. In other words, no special Bootstrap markup or `<div>` wrappers, and no inline validation errors. If you want to display validation errors next to the field you have to do it manually using data from `@obj.errors`.
