### ISSUE TITLE
wrapper not working for time_select

### ISSUE THREAD

**Issue by jpaulomotta** [bootstrap-ruby/rails-bootstrap-forms#224]
Hello guys,

First of all thanks for this excellent gem. I'm using it in a big project.

When I'm trying to use the wrapper attribute with a time_select component it did not work.
I've been using it with text_area, text_field, number_field and select without a problem.

Here's a working snippet

```
    <%= f.number_field :ocupational_stress, wrapper: {class: "row col-sm-6"} %>
    <%= f.number_field :personal_stress, wrapper: {class: "col-sm-6"} %>
    <div class="clearfix"></div>
```

It displays the two fields side by side. There are other fields under it using the same pattern, they're all positioned side by side without any problem.

This does not work

```
    <%= f.time_select :work_from, 
      label: "Work/school schedule including commute (from)",
      wrapper: {class: "row col-sm-6"} 
    %>
    <%= f.time_select :work_to, label: "to", wrapper: {class: "col-sm-6"} %>
    <div class="clearfix"></div>
```

The fields are collapsed vertically and not side by side as the others on the same form. Am I missing something?

Thanks a lot for you help.
JP

**Comment by datWav** [comment]
Hello @jpaulomotta, I think you have the same problem as in #208. Maybe the call should be changed for the time_select fields. =D

**Comment by mattbrictson** [comment]
Cleaning up old unanswered issues. If this question is still relevant, please reopen.
