### ISSUE TITLE
Display inline errors above the field

### ISSUE THREAD

**Issue by abpetkov** [bootstrap-ruby/rails-bootstrap-forms#225]
Is there a way to put the `<span>` error element before the field, rather than rendering it after it? This is for accessibility purposes. What I need is the form to look like this:

``` html
<div class="form-group has-error">
  <label class="control-label" for="user_email">Email</label>
  <span class="help-block">can't be blank</span>
  <input class="form-control" id="user_email" name="user[email]" type="email" value="">
</div>
```

I could use additional JavaScript to move the error block around, but it's a poor solution IMO. I'd rather have an option to set before/after position of the inline error.

**Comment by datWav** [comment]
Hello @abpetkov, I'm sorry to say it but this is not possible with this gem.

**Comment by mattbrictson** [comment]
Cleaning up old unanswered issues. If this question is still relevant, please reopen.
