### ISSUE TITLE
data-toggle='buttons' with Latest Bootstrap 3.3.5

### ISSUE THREAD

**Issue by kntmrkm** [bootstrap-ruby/rails-bootstrap-forms#231]
Hi, I'm using bootstrap-sass gem.

And, I have a code like below.

```
<div data-toggle="buttons">
      <div class="checkbox">
        <label class="btn btn-block btn-facebook " for="post_post_facebook">
          <input name="post[post_facebook]" type="hidden" value="0" />
          <input class="hidden" type="checkbox" value="1" name="post[post_facebook]" id="post_post_facebook" /> Share with Facebook</label>
      </div>
</div>
```

This uses 'button.js' to toggle button as active and checkbox.
[![Gyazo](http://i.gyazo.com/e6692c1a3ff463b6f4237f690a8b79af.gif)](http://gyazo.com/e6692c1a3ff463b6f4237f690a8b79af)

My slim template code is ...

```
= bootstrap_form_for(post) do |f|
  = f.check_box :post_facebook, label: 'Share with Facebook', class: 'hidden',
     label_class: "btn btn-block btn-facebook #{'active' if f.object.post_facebook}"
```

From here is the main issue.

This toggle button works well with Bootstrap-sass 3.3.4.1

but,

Not working with Bootstrap-sass 3.3.5.

This issue does not happen without below code.

`<input name="post[post_facebook]" type="hidden" value="0" />`

Does This input tag need for what?

Anyway This tag prevent Bootstrap's button.js feature.

**Comment by kntmrkm** [comment]
Sorry.

 `<input name="post[post_facebook]" type="hidden" value="0" />`  is default of Rails form.

That means Rails form generator can not use Bootstrap button.js ?

I don't know this issue depend on what....

I'll try a thought.

**Comment by kntmrkm** [comment]
I have posted issue at twbs/bootstrap-sass.

https://github.com/twbs/bootstrap-sass/issues/923

**Comment by kntmrkm** [comment]
I found cause of this issue because of https://github.com/twbs/bootstrap/issues/16693.

check this. which running with TB 3.3.5 latest.
https://jsfiddle.net/kntmrkm/xumxon1L/2/

`label_class` option generate label tag which include two input tag.
TB 3.3.4's button.js works this form. but 3.3.5's button.js does not work this style.

I think that which means `label_class` option should not includes `<input name="post[post_facebook]" type="hidden" value="0" />`. 

How do you think?

**Comment by cvrebert** [comment]
[As noted in the Bootstrap issue](https://github.com/twbs/bootstrap/issues/16693#issuecomment-114835627), the markup currently being produced is not valid HTML. [The HTML5 validator](https://html5.validator.nu/) complains:
> The `label` element may contain at most one `input`, `button`, `select`, `textarea`, or `keygen` descendant.

**Comment by mattbrictson** [comment]
Cleaning up old unanswered issues. If this question is still relevant, please reopen.
