### ISSUE TITLE
Customize style attributes on div with check box

### ISSUE THREAD

**Issue by onebree** [bootstrap-ruby/rails-bootstrap-forms#232]
I am using the default Bootstrap theme/stylesheet on my form. I have the following line in HAML:

``` haml
= f.check_box :mobile_app_access, label: 'Enable'
```

When I check dev tools, the CSS rules state that `margin-top: 10px`, and `margin-bottom: 10px`. This check box resides in a table's cell, and the margin causes the row to be higher than necessary. I want to only change this check box, and not others in the `.checkbox` class.

I have tried the wrapper hash in various ways with no success. Wrappers do not affect the div element, but rather the label element. I essentially want it to be the following (in HTML):

``` html
<div style="margin: 0px;" class="checkbox">
  <label for="location_mobile_app_access">
    <input name="location[mobile_app_access]" value="0" type="hidden">
    <input margin-top="0px" value="1" checked="checked" name="location[mobile_app_access]" id="location_mobile_app_access" type="checkbox">
    Enable
  </label>
</div>
```

**Comment by mattbrictson** [comment]
Cleaning up old unanswered issues. If this question is still relevant, please reopen.
