### ISSUE TITLE
icons for errors

### ISSUE THREAD

**Issue by socalengineer** [bootstrap-ruby/rails-bootstrap-forms#233]
Does this Gem have support for errors with icons?
See the section "With optional icons" for feedback icons.
http://getbootstrap.com/css/#forms

I see that you can add icons to the input fields, but I want the feedback icons to be based if there is an error on the field. Thanks!

**Comment by mattbrictson** [comment]
Cleaning up old unanswered issues. If this question is still relevant, please reopen.
