### ISSUE TITLE
Support for Bootstrap version 4

### ISSUE THREAD

**Issue by crslade** [bootstrap-ruby/rails-bootstrap-forms#237]
I know Bootstrap version 4 is still in Alpha, but I was just wondering what your plan was for Bootstrap v4. I am working on my own custom form builder for v4, but if you want some help, I wouldn't mind forking this and making a bootstrap-v4 branch instead of just building my own.

**Comment by crslade** [comment]
My own version can be found  at [bootstrap4_form_builder](https://github.com/crslade/bootstrap4-form-builder), in case anyone wants to use it. I would be happy to help move this to v4 as well.

**Comment by donv** [comment]
We are using this gem successfully with Bootstrap 4 alpha 3 gem:

https://rubygems.org/gems/bootstrap

**Comment by bradlis7** [comment]
#268

**Comment by mattbrictson** [comment]
See #361
