### ISSUE TITLE
If I use bootstrap_form_tag I get fields id starts with underscore

### ISSUE THREAD

**Issue by Shoroh** [bootstrap-ruby/rails-bootstrap-forms#241]
Suppose we use bootstrap_form_tag:

``` ruby
= bootstrap_form_tag url: categories_path_generator(@category), method: :get do |f|
  = f.select :region, StaticData::REGIONS.map.with_index {|index, region| [index, region] }, include_blank: true, selected: params[:region]
```

Then I got strange **id** of any field starts with underscore:

``` html
id="_region"
```

If I try to use form namespace, like this:

``` ruby
namespace: :ads_form
```

I also get strange **id** with double underscore in the middle:

``` html
id="ads_form__region"
```

I saw the code, it looks like you use form_for without model instead to use form_tag in that case. And first one makes this underscore because is waiting for model/record name.

Also I can't set id of any field manually:

``` ruby
f.text_field :region, id: 'ads_field_region'
or
f.text_field :region, html: { id: 'ads_field_region' }
```

In both cases I get id generated by form_for:

``` html
id="_region"
```

Bug or feature?

**Comment by andenq** [comment]
This is probably a bug? The name also gets surrounded by brackets.

**Comment by mattbrictson** [comment]
Cleaning up old unanswered issues. If this question is still relevant, please reopen.
