### ISSUE TITLE
Append multiple buttons?

### ISSUE THREAD

**Issue by chrismanderson** [bootstrap-ruby/rails-bootstrap-forms#249]
Is it possible to pass multiple buttons to field inputs using `prepend` or `append`? I'm looking at the documentation for http://getbootstrap.com/components/#input-groups-buttons-multiple, and seems like the answer currently no, unless I'm missing something.

http://getbootstrap.com/components/#input-groups-buttons-multiple

**Comment by florentferry** [comment]
Yes, you can. You get a visual issue between two buttons because each one have a border of 1px. 

`append` option take a block, so you can pass your multiple elements to it.

```
append_password_field = [
  link_to("Générer", "#", class: "generate-password btn btn-default"),
  link_to("Voir", "#", class: "toggle-password btn btn-default"),
].join.html_safe

= f.password_field :password, value: f.object.password, append: append_password_field

```

**Comment by mattbrictson** [comment]
Cleaning up old unanswered issues. If this question is still relevant, please reopen.
