### ISSUE TITLE
Make a release?

### ISSUE THREAD

**Issue by rosswilson** [bootstrap-ruby/rails-bootstrap-forms#252]
@potenza It's been a long time since this Gem got a release. Can we get another?

The commit https://github.com/bootstrap-ruby/rails-bootstrap-forms/commit/56dfe373fba7aa32feef633e05059351fb31c1fa fixes a few issues that I've encountered.

**Comment by rosswilson** [comment]
@potenza

**Comment by RKushnir** [comment]
:+1:

**Comment by mattbrictson** [comment]
2.4.0 has been released!
https://rubygems.org/gems/bootstrap_form/versions/2.4.0

**Comment by potenza** [comment]
thanks @mattbrictson for your help with this!
