### ISSUE TITLE
alias_method_chain depricated

### ISSUE THREAD

**Issue by dannytip** [bootstrap-ruby/rails-bootstrap-forms#253]
When using with rails 5 on ruby 2.2.3 the following deprication warning is thrown many times:

`DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super.`

**Comment by dannytip** [comment]
Seems this is fixed in https://github.com/bootstrap-ruby/rails-bootstrap-forms/pull/248

**Comment by rubydev** [comment]
But not merged.

**Comment by wibbly** [comment]
DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super. (called from block in <class:FormBuilder> at /Users/geoff/.rvm/gems/ruby-2.3.0@rails5.0/gems/bootstrap_form-2.3.0/lib/bootstrap_form/form_builder.rb:45)
DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super. (called from block in <class:FormBuilder> at /Users/geoff/.rvm/gems/ruby-2.3.0@rails5.0/gems/bootstrap_form-2.3.0/lib/bootstrap_form/form_builder.rb:58)

Please merge the fix ...
