### ISSUE TITLE
Undefined method 'bootstrap_form_tag'

### ISSUE THREAD

**Issue by PAMulligan** [bootstrap-ruby/rails-bootstrap-forms#257]
The only mention of this error I've been able to find was resolved by uninstalling and reinstalling the gems, but this didn't work for me. My code is as follows:

<%= bootstrap_form_tag url: contact_path do |f| %>
  <%= f.text_field :name, :placeholder => "Name" %>
  <%= f.email_field :email, :placeholder => "E-Mail Address" %>
  <%= f.text_area :message, :placeholder => "Type your message here..." %>
  <%= f.submit %>
<% end %>

**Comment by PAMulligan** [comment]
I shouldn't be calling form_tag on an "f" object, since there's no model associated with it.

**Comment by PAMulligan** [comment]
Still doesn't work even without the call to object "f".

**Comment by mattbrictson** [comment]
Cleaning up old unanswered issues. If this question is still relevant, please reopen.
