### ISSUE TITLE
wrapper does not work with check_box field?

### ISSUE THREAD

**Issue by ved54321** [bootstrap-ruby/rails-bootstrap-forms#260]
I have added checkbox field like this 
<%= f.check_box :create_ug,label: 'Create User Group',wrapper: { class: 'createUserGroupQuestions', data: { foo: 'bar' } } %>
which created following html,

<div class="checkbox"><label for="union_questions_attributes_0_create_ug"><input type="hidden" value="0" name="union[questions_attributes][0][create_ug]"><input type="checkbox" id="union_questions_attributes_0_create_ug" name="union[questions_attributes][0][create_ug]" checked="checked" value="1" wrapper="{:class=&gt;&quot;createUserGroupQuestions&quot;, :data=&gt;{:foo=&gt;&quot;bar&quot;}}"> Create User Group</label></div>

How will i add class to main wrapper similar to this,
<div class="checkbox createUserGroupQuestions ">

Please help?

**Comment by mattbrictson** [comment]
Cleaning up old unanswered issues. If this question is still relevant, please reopen.
