### ISSUE TITLE
How to just render a simple form_group

### ISSUE THREAD

**Issue by prakashraman** [bootstrap-ruby/rails-bootstrap-forms#270]
Hi,

I would like to use the helper to create a simple input group field. It might not be part of a form, or the form might not have any action to it.

How could I achieve this without having to use 

_form_for_

Thanks!

**Comment by mattbrictson** [comment]
Have you tried using `fields_for` as described in this blog post?

https://solidfoundationwebdev.com/blog/posts/use-form_for-or-simple_form_for-methods-without-any-form-tag-in-rails

**Comment by mkon** [comment]
when using `fields_for` there is no access to the bootstrap form helpers however.

**Comment by mattbrictson** [comment]
@mkon Does this work?

```ruby
fields_for(..., builder: BootstrapForm::FormBuilder) do |f|
  ...
end
```

**Comment by mkon** [comment]
Yes thanks this works!
