### ISSUE TITLE
Rename btn-default by btn-secondary for bootstrap 4 support

### ISSUE THREAD

**Issue by jonathantribouharet** [bootstrap-ruby/rails-bootstrap-forms#271]
Here the link suggesting to rename according to the migration:
http://v4-alpha.getbootstrap.com/migration/#buttons

But if you look at the form exemple, they replace `btn-default` by `btn-primary`, which seems more logic:
http://v4-alpha.getbootstrap.com/components/forms/

Thank's

**Comment by mattbrictson** [comment]
Can you add this suggestion as a comment to #268? That's where a discussion has already started regarding Bootstrap 4 changes.
