### ISSUE TITLE
label_class:"checkbox-inline" not working

### ISSUE THREAD

**Issue by pablougas** [bootstrap-ruby/rails-bootstrap-forms#279]
Is this class available for the gem?

**Comment by mattbrictson** [comment]
Can you explain a little more what code you trying, and the output you are expecting? Thanks!

**Comment by pablougas** [comment]
Yes, I have 6 checkboxes in a regular bootstrap_form_for that I would like to appear inline with each other instead of under one another. I added `label_class: checkbox-inline` per the [bootstrap site](http://v4-alpha.getbootstrap.com/components/forms/#inline) but doesn't seem to change anything...

**Comment by mattbrictson** [comment]
Use `inline: true` and it should do the right thing.

E.g.

```erb
<%= f.check_box(:example, label: "I'm inline!", inline: true ) %>
```

**Comment by mattbrictson** [comment]
Here's the documentation in our README:

https://github.com/bootstrap-ruby/rails-bootstrap-forms#checkboxes-and-radios

Let me know if you have any trouble getting it to work. Otherwise I'll consider this closed.
