### ISSUE TITLE
how do i change the date select format 

### ISSUE THREAD

**Issue by webofbits** [bootstrap-ruby/rails-bootstrap-forms#286]
#I want to change to dd/mm/yyy based in my country convention (brazil).

**Comment by mattbrictson** [comment]
Hi, the bootstrap_form gem simply wraps the Rails `date_select` helper, so you can refer to the official Rails documentation here:

http://api.rubyonrails.org/v4.2.7/classes/ActionView/Helpers/DateHelper.html#method-i-date_select

Hope that helps!
