### ISSUE TITLE
Checkbox field validation error missing

### ISSUE THREAD

**Issue by gliwka** [bootstrap-ruby/rails-bootstrap-forms#287]
## Expected behavior:

Validation errors for checkboxes should be displayed like for any other component.
## Observed behavior:

The error message for the checkbox is missing.

![screenshot from 2016-08-19 13-25-39](https://cloud.githubusercontent.com/assets/4993665/17808441/77f1c022-6610-11e6-9003-14375bfdcefa.png)
## Related Code Snippets

account.rb

```
class Account < ApplicationRecord
<...>
  validates_acceptance_of :privacy_agreement
<....>
end
```

new.html.erb

```
<...>
              <%= f.form_group :privacy_agreement do %>
                <%= f.check_box :privacy_agreement, label: "I agree to the Privacy Agreement" %>
              <% end %>
<...>
```

Any ideas?

Best,
Matthias

**Comment by mattbrictson** [comment]
Thanks very much for the report!

Hmm, your code looks correct. I'm pretty sure this was working at some point. I'll see if I can reproduce the problem.

**Comment by gliwka** [comment]
Do you need any more details? 

I encountered this error using Rails 5. Also, when i use  `<%= f.alert_message "Please fix the errors below." %>`, the validation error is part of the summary.

**Comment by mattbrictson** [comment]
Sorry, I haven't had time to look into this further. If anyone else wants to take over, please jump in!

**Comment by mattbrictson** [comment]
Hi, I tried reproducing this issue, but it seems to work fine for me.

rails 5.0.0.1
bootstrap_form 2.5.0

My model:

```ruby
create_table "posts", force: :cascade do |t|
  t.string   "title"
  t.text     "body"
  t.boolean  "draft"
  t.datetime "created_at", null: false
  t.datetime "updated_at", null: false
end

class Post < ApplicationRecord
  validates_presence_of :title
  validates_acceptance_of :draft
end
```

View:

```erb
<%= bootstrap_form_for(post) do |f| %>
  <%= f.text_field :title %>
  <%= f.text_area :body %>
  <%= f.form_group :draft do %>
    <%= f.check_box :draft, label: "I agree to the Privacy Agreement" %>
  <% end %>

  <%= f.primary %>
<% end %>
```

This is with a brand-new `rails new` app with no changes other than adding `bootstrap_form` to the Gemfile.

If you are still having the problem, could you create a basic Rails app the demonstrates the bug and post a link to the code? That would help.

**Comment by mattbrictson** [comment]
![screen shot 2016-08-26 at 1 30 26 pm](https://cloud.githubusercontent.com/assets/189693/18019646/ee558420-6b91-11e6-895b-0022b5d9e968.png)

**Comment by gliwka** [comment]
Thanks for your feedback, sorry for the late response.

I've created a fresh app, and it's working now.

I'll close the issue.
