### ISSUE TITLE
Disable label rendering

### ISSUE THREAD

**Issue by DenniJensen** [bootstrap-ruby/rails-bootstrap-forms#288]
Hey,

is there any possibility I can use `bootstrap_form_for` without generating the label-tag?
I want to build an inline form field with selects and date input, but without all the label tags.

Code.
![image](https://cloud.githubusercontent.com/assets/3010752/17861189/0911d76e-685e-11e6-9e03-a20d5271df6c.png)

Web.
![image](https://cloud.githubusercontent.com/assets/3010752/17861240/39cafee4-685e-11e6-8ff2-b1600acdb1f0.png)

I want to remove the labels before each input field or select box.

**Comment by mattbrictson** [comment]
Yes, can you try using the `skip_label: true` option? Like this:

```ruby
f.date_field :vacated_at, skip_label: true
```

**Comment by DenniJensen** [comment]
Thank you very much
