### ISSUE TITLE
Adding icon to buttons

### ISSUE THREAD

**Issue by Antronin** [bootstrap-ruby/rails-bootstrap-forms#297]
Is there a way to add icon to a primary button?

**Comment by krsyoung** [comment]
Was curious about the same thing however @mattbrictson I think your above suggestion works perfectly.

Not sure if there is an adequate motivation to add a helper for it?  If anything maybe the above example in https://github.com/bootstrap-ruby/rails-bootstrap-forms#submit-buttons would suffice?

@Antronin do you see a gap / have an idea what the proposed helper would look like?

**Comment by mattbrictson** [comment]
Closing since I think my suggested solution is adequate.
