### ISSUE TITLE
Provide support for usage with non-ActiveRecord models

### ISSUE THREAD

**Issue by nicosuave** [bootstrap-ruby/rails-bootstrap-forms#310]
[This](https://github.com/bootstrap-ruby/rails-bootstrap-forms/blob/master/lib/bootstrap_form/form_builder.rb#L117) fallback doesn't seem to work as intended. There should be another check to verify if the object responds to `human_attribute_name` prior to actually calling it

[Another example](https://github.com/bootstrap-ruby/rails-bootstrap-forms/blob/master/lib/bootstrap_form/form_builder.rb#L379)

**Comment by mattbrictson** [comment]
Thanks for the report! Could you provide some sample code that shows how you'd use this feature in practice? I'm going to add the **you can help!** label to this issue to encourage PR contributions.

**Comment by nicosuave** [comment]
I am closing this after some more consideration. We employ a microservice architecture and some of our service-specific HTTP clients return something close to a PORO. We ended up using FormObjects to provide these methods.
