### ISSUE TITLE
Shouldnt be the errormessage be text-danger, by default?

### ISSUE THREAD

**Issue by krtschmr** [bootstrap-ruby/rails-bootstrap-forms#317]
just curios that the errormessages for each field are not colored. shouldn't they be text-danger by default?

```

.form-group.has-error .help-block {
  color: $brand-danger;
}
```

**Comment by mattbrictson** [comment]
Bootstrap uses `.has-error` to color error messages, as documented here:

http://getbootstrap.com/css/#forms-control-validation

And `.has-error` does indeed use `$brand-danger` as you can see in the Bootstrap code here:

https://github.com/twbs/bootstrap/blob/9b7d1406b922300c5d01e99026e4fffc67445185/less/forms.less#L434-L436

Is it possible that you have CSS in your app that is overriding the default Bootstrap styles?

**Comment by GBH** [comment]
This should be closed. Not relevant to Bootstrap 4 anymore.
