### ISSUE TITLE
In case of multiple errors, how to output only the first one?

### ISSUE THREAD

**Issue by AlexanderMint** [bootstrap-ruby/rails-bootstrap-forms#320]
How to make that only the one (first) error was output?

**Comment by mattbrictson** [comment]
I don't think this something that you can easily control within `bootstrap_form` itself.

If this is something you'd like to do for your entire app, you could monkey patch `BootstrapForm::FormBuilder#get_error_messages` to use only the first error.

Alternatively, if it is for a specific model (or attribute of a model), you could modify your validators on the model to ensure only one error message is ever recorded.

What is your specific use case?

**Comment by mattbrictson** [comment]
Cleaning up old unanswered issues. If this question is still relevant, please reopen.
