### ISSUE TITLE
How to set "inline_errors" or "label_errors" options globally? 

### ISSUE THREAD

**Issue by starcharles** [bootstrap-ruby/rails-bootstrap-forms#321]
I'm now developing Rails4 app using this bootstrap-forms. 
But I want suppress error message , using "inline_errors: false, label_errors: false".

here , I write the same options at many forms.
```
<%= bootstrap_form_for(******, inline_errors: false, label_errors: false) do |f| %>
```

Can I set error display options globally, by writing options in any place in my app. 
Should I make original config files?

**Comment by mattbrictson** [comment]
You could write a helper:

```ruby
module ApplicationHelper
  def custom_form_for(*args, &block)
    opts = args.extract_options!
    bootstrap_form_for(*args, opts.reverse_merge(inline_errors: false, label_errors: false), &block)
  end
end
```

And then use `custom_form_for` throughout your app.

**Comment by starcharles** [comment]
@mattbrictson 
Thanks for your approach to use custom helper. But if I don't want to change name 'bootstrap_form_for' to 'custom_form_for' in all of my app codes, is there any smart ways to set these additional options?

**Comment by mattbrictson** [comment]
No, to my knowledge there is no global configuration for this.

**Comment by starcharles** [comment]
I understand. I will try to use custom_form_for in my app.
Thank you!
