### ISSUE TITLE
How to append an HTML element to an input's wrapper <div>?

### ISSUE THREAD

**Issue by abevoelker** [bootstrap-ruby/rails-bootstrap-forms#328]
Apologies if I'm missing something obvious, but is there a way to append an HTML element to the `<div class="form-group">` wrapper generated by an input helper?

For example, [the first form example](https://v4-alpha.getbootstrap.com/components/forms/#form-controls) in the Bootstrap 4 docs includes a `<small>` element after the label and input elements for providing additional help text:

![screenshot from 2017-04-30 13-23-15](https://cloud.githubusercontent.com/assets/153459/25566870/329946b6-2da8-11e7-8533-0b8d59b4196a.png)

```html
<div class="form-group">
  <label for="exampleInputEmail1">Email address</label>
  <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
  <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
</div>
```

Is there a way to do this with the current form helpers? I saw some other answers that used the `:append` option with `html_safe`, so I tried that but didn't get the output I was looking for:

```ruby
<%= f.email_field :email, autofocus: true, append: '<small id="emailHelp" class="form-text text-muted">We\'ll never share your email with anyone else.</small>'.html_safe %>
```

![screenshot from 2017-04-30 13-23-01](https://cloud.githubusercontent.com/assets/153459/25566878/489af310-2da8-11e7-8c1d-4184522fa256.png)

```html
<div class="form-group">
  <label class="form-control-label required" for="user_email">Email</label>
  <div class="input-group">
    <input autofocus="autofocus" class="form-control" type="email" value="" name="user[email]" id="user_email">
    <span class="input-group-addon"><small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small></span>
  </div>
</div>
```

I also tried wrapping it in a `f.form_group` block, thinking that maybe this let me define the form-group block more explicitly, but as you probably already know that just adds an extra form-group div wrapper, which makes the spacing wrong:

```ruby
<%= f.form_group do %>
  <%= f.email_field :email, autofocus: true %>
  <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
<% end %>
```
![screenshot from 2017-04-30 13-38-58](https://cloud.githubusercontent.com/assets/153459/25567014/64083fa2-2daa-11e7-9777-9c9147a6de46.png)

```html
<div class="form-group">
  <div class="form-group">
    <label class="form-control-label required" for="user_email">Email</label>
    <input autofocus="autofocus" class="form-control" type="email" value="" name="user[email]" id="user_email">
  </div>
  <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
</div>
```

I ended up using `text_field_without_bootstrap`, which works totally fine of course:

```erb
<div class="form-group">
  <%= f.label :email %>
  <%= f.text_field_without_bootstrap :email, class: "form-control", type: "email", autofocus: true %>
  <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
</div>
```

Just wondering if I'm missing anything! Also thanks a lot for this gem.

**Comment by abevoelker** [comment]
Okay I see now that the `:help` option is for this specific example use case (although generates a `<span>`). Which is good because I realized what I was doing wasn't handling error messages :smile:.

However, it seems that form errors replace the help text message, which is something I don't want (see [the bootstrap example of help text not erasing](https://v4-alpha.getbootstrap.com/components/forms/#examples)).

So am still somewhat curious if there's a more general solution for adding arbitrary elements or not.

I also tested #259's PR, but `wrapper: false` seems to not generate the corresponding `<label>` for the `<input>` so wasn't quite what I was looking for.

**Comment by mattbrictson** [comment]
To my knowledge, `:help` is the "official" way to accomplish what you are looking for. In the more general case, I don't think there is a way to append arbitrary markup within the wrapper `<div>`.

Regarding the error overriding the `:help`, there is a separate issue for discussing that if you want to add your 2¢. Thanks!

https://github.com/bootstrap-ruby/rails-bootstrap-forms/issues/284

**Comment by abevoelker** [comment]
Sounds good, thanks!
