### ISSUE TITLE
i18n translations for labels

### ISSUE THREAD

**Issue by sekrett** [bootstrap-ruby/rails-bootstrap-forms#335]
I don't understand why this does not work?

Rails 5.1.2
bootstrap_form 2.7.0

```yaml
ru:
  activerecord:
    attributes:
      email_queue:
        name: Название
```

When I replace `attributes` with `help` it works but it is a different thing, I need labels. Readme says "bootstrap_form follows standard rails conventions so it's i18n-ready" but it does not.

Of course I could do:

```= f.text_field :name, label: t('activerecord.attributes.email_queue.name')```

but it makes forms heavy.

**Comment by sekrett** [comment]
I have written a small module as a workaround:

```ruby
module BootstrapFormTranslation
  BootstrapForm::FormBuilder::FIELD_HELPERS.each do |method_name|
    define_method(method_name) do |name, options = {}|
      options.merge!(
        label: I18n.t("activerecord.attributes.#{object_name}.#{name}")
      )
      super(name, options)
    end
  end
end

BootstrapForm::FormBuilder.send(:prepend, BootstrapFormTranslation)
```

**Comment by sekrett** [comment]
Error messages are in english regardless my settings in `application.rb`:

```ruby
    config.i18n.default_locale = :ru
```

**Comment by mattbrictson** [comment]
Thanks for the detailed bug report! I've used bootstrap_form with i18n in the past and it worked as expected. Perhaps a bug has crept in or Rails 5.1 changed something recently. I'll try to find time to investigate this further this week.

**Comment by sekrett** [comment]
I don't understand, where does it come from "is not present". This exact phrase cannot be found in rails source or in this gem. It means even in english a yaml file is not loaded. Is it built dynamically? I believe normally rails should say "can't be blank".

**Comment by mattbrictson** [comment]
I researched this and found that the correct way to translate the labels is as follows:

```yaml
ru:
  helpers:
    label:
      email_queue:
        name: Название
```

This is according to the documentation here: http://api.rubyonrails.org/classes/ActionView/Helpers/FormHelper.html#method-i-label

I tested this with `bootstrap_form` and it works for me.

The "is not present" vs "can't be blank" problem is probably unrelated to bootstrap_form.

**Comment by sekrett** [comment]
Nice, thanks. So it works on Rails 5.1 with ActiveRecord and does not with Sequel.

The documentation also says:

> Localization can also be based purely on the translation of the attribute-name (if you are using ActiveRecord)

and it does not work with `bootstrap_form`. So all together is confusing, some variants work with `activerecord` attributes but without ActiveRecord installed and vice versa. I think I will use my little patch for now.

Yes, error messages are not related to `bootstrap_form`, as I told earlier, they are generated by the model.

**Comment by sekrett** [comment]
There is one more problem. :) In my view I added:

```haml
= t('helpers.label.email_queue.description')
= t('flash.email_queue.create')
```

First line is in english, second is in russian. But both translations are in the same `yml` file. Now I am finally confused. And if I change my patch to use `helpers.label` it explicitly says on inputs `translation missing: ru.helpers.label.email_queue.name`. So better to avoid `helpers` hash, I don't know what kind of magic is there.

**Comment by mattbrictson** [comment]
> activerecord/attributes also should work

That's what the documentation says, but I couldn't get it to work even with plain Rails (i.e. no `bootstrap_form`). The `helpers` approach definitely works.

I'll close this because I don't believe it is a `bootstrap_form`-specific issue.

**Comment by sekrett** [comment]
Ok, sure, so it is a Rails bug, not yours.

**Comment by SaimonL** [comment]
I am using Rails 5.1.3 and still having this problem where setting:
```yaml
en:
  activerecord:
    attributes:
      user:
        display_name: 'Your display name'
```
don't work. However not using bootstrap_form_for works just fine.

I ended up using `sekrett` workaround.
```ruby
module BootstrapFormTranslation
  BootstrapForm::FormBuilder::FIELD_HELPERS.each do |method_name|
    define_method(method_name) do |name, options = {}|
      key = "activerecord.attributes.#{object_name}.#{name}"
      options.merge!(label: I18n.t(key)) unless translation_missing?(key)
      super(name, options)
    end
  end
end

BootstrapForm::FormBuilder.send(:prepend, BootstrapFormTranslation)

def translation_missing?(key)
  I18n.t(key)[0..20] == 'translation missing: '
end
```
