### ISSUE TITLE
Support for sass

### ISSUE THREAD

**Issue by PAMulligan** [bootstrap-ruby/rails-bootstrap-forms#337]
I'm using the rails bootstrap gem (https://github.com/twbs/bootstrap-rubygem), which requires scss for it's stylesheets. I'm having trouble importing rails_bootstrap_forms in my application.scss, I'm getting the error message "File to import not found or unreadable: rails_bootstrap_forms". Is scss supported with this gem, or are there plans to integrate that?

**Comment by mattbrictson** [comment]
Yes, SCSS is absolutely supported. Are you sure you added the gem to your `Gemfile` and ran `bundle install`?

This works for me:

**Gemfile**

```ruby
gem "bootstrap-sass", "~> 3.2"
gem "bootstrap_form", "~> 2.7"
```

**app/stylesheets/application.scss**

```scss
@import "bootstrap";
@import "rails_bootstrap_forms";
```

**Comment by PAMulligan** [comment]
Unfortunately, I'm still getting that error message. My Gemfile has: 

    gem 'bootstrap', git: 'https://github.com/twbs/bootstrap-rubygem'
    gem 'bootstrap-sass', '~> 3.2'
    gem 'bootstrap_form', '~> 2.7'

And my application.scss has:

    @import 'bootstrap';
    @import 'rails_bootstrap_forms';

My form tag starts like this:

    <%= bootstrap_form_for(@listing) do |f| %>

I'm using Rails 5.1.2, if that makes a difference

**Comment by mattbrictson** [comment]
Thanks for the additional info. As an aside: Why do you have both `bootstrap` and `bootstrap-sass` gems? Doesn't that mean you are requiring two versions of Bootstrap (v3 and v4)? That's probably not related to the `rails_bootstrap_forms` issue, but it seems like it would cause problems.

Anyway, have you tried stopping Spring and then rebooting your Rails app?

```
$ bin/spring stop
```

**Comment by PAMulligan** [comment]
I added the bootstrap-sass gem after your comment, that wasn't there before. With or without that gem, I got the same result. I will try stopping Spring and rebooting when I hop back on, thank you for the advice.

**Comment by mattbrictson** [comment]
If you are aiming for Bootstrap v4, then you should use this branch:

```ruby
gem "bootstrap_form ", github: "bootstrap-ruby/rails-bootstrap-forms" , branch: "bootstrap-v4"
```

**Comment by PAMulligan** [comment]
That solved it, thank you.
