### ISSUE TITLE
Mark invalid fields with .is-invalid instead of has-danger for Bootstrap 4 (beta)

### ISSUE THREAD

**Issue by donv** [bootstrap-ruby/rails-bootstrap-forms#339]
Bootstrap 4 beta is now out, promising no more breaking changes.  Maybe make V4 the master?

Anyway, form fields should now be marked with `.is-invalid` or `.is-valid` depending on status.

The help text should be marked with `.invalid-feedback`.

Reference:  https://getbootstrap.com/docs/4.0/components/forms/

**Comment by mattbrictson** [comment]
@donv can you confirm this issue has been fixed via #370?

**Comment by donv** [comment]
Indeed, this has been fixed!
