### ISSUE TITLE
Set min/max year on date_field

### ISSUE THREAD

**Issue by clveranis** [bootstrap-ruby/rails-bootstrap-forms#341]
Hi, so I've been searching all over and trying to figure out where the calendar drop down comes from for the date_field input so that way I can set some type of validation on it in the same way that if you try to type in the month '13' or even '02/31/xxxx', it will automatically notify you to select a valid date. However, I can type in '01/01/0001' or '05/31/9999' and those are valid and I would like to prevent that from occurring. If date_field is smart enough to know there are only 27/28 days in February and only 12 months in a year, then it stands to reason that there is the ability to only allow years 1800-2200 or the like. 

So is there a way I can dig into this and set it and/or where does it pull that calendar drop down from? Thanks!

**Comment by mattbrictson** [comment]
Hi, can you post the code that you are using to produce the calendar? I am not sure I understand what you are referring to. Thanks!

If you are using the Rails helpers like `date_select`, then you can provide `:start_year` and `:end_year` options as documented here:

http://api.rubyonrails.org/classes/ActionView/Helpers/DateHelper.html#method-i-date_select

**Comment by clveranis** [comment]
`<%= bootstrap_form_for(@properties, layout: :horizontal, remote: true) do |f| %>
       
...
            <%= f.date_field :installment_date1, label: "First Tax Installment Date", class: 'form-control' %>            
            <%= f.date_field :installment_date2, label: "Second Tax Installment Date", class: 'form-control' %>

...
            <%= f.form_group do %>
                <%= f.submit "Update Tax Info", class: "btn btn-primary" %>
            <% end %>

  <% end %>`

Just using that `date_field` helper will then produce a '__/__/____'  format within the field and also adds a dropdown arrow on the side of the field that pops out a calendar. Basically I want to be able to limit the ability to enter or select a year before say 1900 and after 2200, something along those lines. I've included a picture if that helps. Thanks!

<img width="1162" alt="bootstrap_calandar_picker" src="https://user-images.githubusercontent.com/26399853/29597935-d0287222-8793-11e7-8179-443d20060ed0.png">

**Comment by mattbrictson** [comment]
Ah, I see. Thanks for clarifying.

I don't believe this is related to the `bootstrap_form` gem at all. The behavior you see is provided by the web browser, not by Rails or Bootstrap. Here is the Rails documentation:

http://api.rubyonrails.org/v4.2.7.1/classes/ActionView/Helpers/FormHelper.html#method-i-date_field

Based on the doc, it sounds like you can use `:start` and `:end` options.

Here is Mozilla's documentation of the browser behavior that I mentioned with more explanation of the supported options:

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date

If you find a case where the options work when `date_field` is used within `form_for` but do not work within `bootstrap_form_for`, then there could be a bug. If so, let me know and I'll re-open this issue.

Good luck!

**Comment by clveranis** [comment]
Oh my fault! I didn't realize. Thank you very much for the quick and insightful response. Love the gem and keep up the great work! Thanks!
