### ISSUE TITLE
Bad Select example in README

### ISSUE THREAD

**Issue by josedusol** [bootstrap-ruby/rails-bootstrap-forms#351]
Hello. The Select example in README file is wrong, elements are in bad order. It should be:

`<%= f.select :product, [["Apple", 1], ["Grape", 2]], { label: "Choose your favorite fruit:" }, { class: "selectpicker" } %>`

**Comment by mattbrictson** [comment]
Good catch, thanks! Would you mind creating a PR? Just view the README and click the pencil icon to make the change and GitHub will guide you to creating the PR.

https://github.com/bootstrap-ruby/rails-bootstrap-forms/blob/master/README.md

**Comment by mattbrictson** [comment]
Fixed by #355
