### ISSUE TITLE
Bootstrap 4 form-group there's no more offset classes

### ISSUE THREAD

**Issue by GBH** [bootstrap-ruby/rails-bootstrap-forms#353]
https://github.com/bootstrap-ruby/rails-bootstrap-forms/blob/bootstrap-v4/lib/bootstrap_form/form_builder.rb#L215

Need to add column div in place of the label.

**Comment by mattbrictson** [comment]
Could you clarify or provide a code sample? It seems that `offset` classes are still part of the v4 grid system: <http://getbootstrap.com/docs/4.0/layout/grid/#offsetting-columns>. Am I misunderstanding?

**Comment by GBH** [comment]
Crazy. Probably brought it back with beta3. Wasn't there in beta2.
