### ISSUE TITLE
Handling additional FormHelper method

### ISSUE THREAD

**Issue by Hugo-Hache** [bootstrap-ruby/rails-bootstrap-forms#356]
I just published a gem to add the regex_field method to the Rails FormHelper https://github.com/applidium/regex_field. 

Currently in my own project I bootstrap it with this code:

`/lib/bootstrap_form/regex_field`
```
module BootstrapForm
  module RegexFormBuilder
    extend ActiveSupport::Concern

    included do
      bootstrap_method_alias :regex_field
    end

    def regex_field_with_bootstrap(name, options = {})
      form_group_builder(name, options) do
        prepend_and_append_input(options) do
          regex_field_without_bootstrap(name, options)
        end
      end
    end
  end
end
```

`/config/initializers/bootstrap_form.rb`
```
BootstrapForm::FormBuilder.send(:include, BootstrapForm::RegexFormBuilder)
```

First question: do you see any better way to do this ? 
Second question: what do you think of making possible to add fields to [FIELD_HELPERS](https://github.com/bootstrap-ruby/rails-bootstrap-forms/blob/0fac4b176e753e2883b6632ab62926981cc88550/lib/bootstrap_form/form_builder.rb#L11) ?

**Comment by GBH** [comment]
I think they way you're extending form builder is fine. I don't think that bootstrap_form needs this though. It should only wrap exiting helpers coming from rails.

**Comment by mattbrictson** [comment]
Agreed; currently our goal is to wrap existing Rails helpers only. I think arbitrary extensibility is beyond the scope of the gem. I'll close this for now.
