### ISSUE TITLE
I'm Willing to Help

### ISSUE THREAD

**Issue by lcreid** [bootstrap-ruby/rails-bootstrap-forms#358]
@mattbrictson , @koenpunt things seem quiet in this repo over the last six months. I'd be willing to help in some way if you would be willing to give me some pointers. Feel free to email me at lcreid@jadesystems.ca if you think the conversation would go better via e-mail.

**Comment by mattbrictson** [comment]
@lcreid thanks for the generous offer! I'll contact you via email.
