### ISSUE TITLE
Add support for cocoon

### ISSUE THREAD

**Issue by wingrunr21** [bootstrap-ruby/rails-bootstrap-forms#91]
[cocoon](https://github.com/nathanvda/cocoon) is another nested form handler. Add support for this.

Since cocoon appears to not require form_builder integration, this may be just a matter of detecting the gem and enabling the nested_form method.

**Comment by jamiek23** [comment]
Just to provide a little bit of feedback on this one - cocoon and bootstrap forms appear to play quite nicely together. I haven't really encountered any issues - f.fields_for is present, so it all seems to work.

**Comment by mattbrictson** [comment]
Closing since the latest comment indicates this is already working.
